# Libraries

In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.metrics import classification_report
import scikitplot as skplot
#from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import StandardScaler 
#from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
#from sklearn.linear_model import LogisticRegression
#from sklearn.neighbors import KNeighborsClassifier
#from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score
from sklearn.metrics import r2_score,mean_squared_error

# Acquire Data

In [28]:
df_train = pd.read_excel('20220819_NewDecanter_AfterCleansingAndEDA.xlsx') # Importing our training dataset

In [29]:
df_train.head()

T_5551     T_5554     T_5552  Decanter_Flowrate  Temp_Bearing_NDE  \
0  67.936150  77.467194  52.334980           5.067348         44.074169   
1  67.835419  68.610298  48.186638           4.781287         44.220940   
2  65.903542  81.915855  45.028320           5.216979         44.317516   
3  64.512802  71.935173  48.777279           4.877123         44.309498   
4  62.900108  78.755104  50.602764           5.097422         52.409241   

   Temp_Bearing_DE  Vibration_Feed  Vibration_Driver  Vibration_Frame  \
0        52.407757        3.266149          1.093617         3.461218   
1        52.260834        2.478317          2.430974         2.422086   
2        51.881176        0.836691          2.622614         0.539779   
3        51.664837        3.003732          1.120057         3.132683   
4        83.077713        3.611319          1.527769         4.074305   

   Blow_Speed_RPM  Diff_Speed_RPM    Torque  Severity  
0     3179.257568        1.404776  3.194033         3  
1     3181.251953        1.406971  3.037234         3  
2     3180.539795        1.404714  2.844089         3  
3     3179.219482        1.408366  4.396934         3  
4     3179.277100        1.407362  3.685323         3

In [30]:
df_train.tail()

T_5551     T_5554     T_5552  Decanter_Flowrate  Temp_Bearing_NDE  \
2627  52.66777  73.753344  59.091043           4.438022         49.765103   
2628  52.66777  73.753344  59.091043           4.438022         49.765103   
2629  52.66777  73.753344  59.091043           4.438022         49.765103   
2630  52.66777  73.753344  59.091043           4.438022         49.765103   
2631  52.66777  73.753344  59.091043           4.438022         49.765103   

      Temp_Bearing_DE  Vibration_Feed  Vibration_Driver  Vibration_Frame  \
2627        54.360617           22.60              25.0             21.0   
2628        54.360617           24.02              23.0             16.0   
2629        54.360617           26.89              16.0             22.0   
2630        54.360617           19.99              14.0             20.0   
2631        54.360617           25.67              23.0             16.8   

      Blow_Speed_RPM  Diff_Speed_RPM    Torque  Severity  
2627     3160.720527        1.349073  4.439894         4  
2628     3160.720527        1.349073  4.439894         4  
2629     3160.720527        1.349073  4.439894         4  
2630     3160.720527        1.349073  4.439894         4  
2631     3160.720527        1.349073  4.439894         4

In [31]:
df_train.shape

(2632, 13)

In [32]:
X = df_train.iloc[:,0:12].to_numpy() # Making training set

In [33]:
X.shape

(2632, 12)

In [34]:
X

array([[6.79361496e+01, 7.74671936e+01, 5.23349800e+01, ...,
        3.17925757e+03, 1.40477645e+00, 3.19403315e+00],
       [6.78354187e+01, 6.86102982e+01, 4.81866379e+01, ...,
        3.18125195e+03, 1.40697062e+00, 3.03723359e+00],
       [6.59035416e+01, 8.19158554e+01, 4.50283203e+01, ...,
        3.18053979e+03, 1.40471375e+00, 2.84408927e+00],
       ...,
       [5.26677702e+01, 7.37533438e+01, 5.90910427e+01, ...,
        3.16072053e+03, 1.34907322e+00, 4.43989426e+00],
       [5.26677702e+01, 7.37533438e+01, 5.90910427e+01, ...,
        3.16072053e+03, 1.34907322e+00, 4.43989426e+00],
       [5.26677702e+01, 7.37533438e+01, 5.90910427e+01, ...,
        3.16072053e+03, 1.34907322e+00, 4.43989426e+00]])

In [35]:
y = df_train.iloc[:,12].to_numpy() # Making labels

In [36]:
y.shape

(2632,)

In [37]:
y

array([3, 3, 3, ..., 4, 4, 4], dtype=int64)

In [38]:
features_list = list(df_train.columns[0:12])

In [39]:
features_list

['T_5551',
 'T_5554',
 'T_5552',
 'Decanter_Flowrate',
 'Temp_Bearing_NDE',
 'Temp_Bearing_DE',
 'Vibration_Feed',
 'Vibration_Driver',
 'Vibration_Frame',
 'Blow_Speed_RPM',
 'Diff_Speed_RPM',
 'Torque']

# Scaling Numerical Data

In [40]:
#scaler = StandardScaler()

In [41]:
#scaler.fit(X)

In [42]:
#X = scaler.transform(X) # The dataset is now scaled from 0-1

In [43]:
#X

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 2022, shuffle=True, stratify=y) 
# Train/test split with 20% test size

# Build Models

Machine learning models that will be used are
- LogisticRegression
- KNeighborsClassifier
- RandomForestClassifier

# Random Forest_Regressor

In [45]:
# # Create the parameter grid based on the results of random search 
#param_grid = {
#    'bootstrap': [True],
#    'max_depth': [80, 90, 100],
#    'max_features': [2, 3],
#    'min_samples_leaf': [3, 4, 5],
#    'min_samples_split': [8, 10, 12],
#    'n_estimators': [100, 200, 300]
#}
## Create a based model
#rfr = RandomForestRegressor()
## Instantiate the grid search model
#grid_search = GridSearchCV(estimator = rfr, param_grid = param_grid, 
#                          cv = 3, n_jobs = -1, verbose = 2)

In [46]:
# Create the parameter grid based on the results of random search 
param_grid = {
    'bootstrap': [True],
    'max_depth': [100],
    'max_features': [3],
    'min_samples_leaf': [3],
    'min_samples_split': [8],
    'n_estimators': [200]
}
# Create a based model
rfr = RandomForestRegressor()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rfr, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2)

In [47]:
# Fit the grid search to the data
grid_search.fit(X_train, y_train)
#grid_search.best_params_

Fitting 3 folds for each of 1 candidates, totalling 3 fits


GridSearchCV(cv=3, estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'bootstrap': [True], 'max_depth': [100],
                         'max_features': [3], 'min_samples_leaf': [3],
                         'min_samples_split': [8], 'n_estimators': [200]},
             verbose=2)

In [48]:
grid_search.best_params_

{'bootstrap': True,
 'max_depth': 100,
 'max_features': 3,
 'min_samples_leaf': 3,
 'min_samples_split': 8,
 'n_estimators': 200}

In [49]:
y_test_pred_rfr = grid_search.predict(X_test)
acc_rfr_r2_score = r2_score(y_test, y_test_pred_rfr)
print(acc_rfr_r2_score)

0.9098357957301014


In [50]:
y_test_pred_rfr = grid_search.predict(X_test)
acc_rfr_mean_squared_error = mean_squared_error(y_test, y_test_pred_rfr)
print(acc_rfr_mean_squared_error)

0.03378872948810713


# Model Evaluation

# Conclusion

The best predictors based on accuracy score are Random Forest, follows by k-Nearest Neighbors, and Logistic Regression. The best parameters are as follows

# Making Submission File

In [32]:
df_pred = pd.read_excel('20220819_NewDecanter-RawData_20220805-20220814_Implement.xlsx')

In [33]:
df_pred

Date     T-5551     T-5554     T-5552  Decanter Flowrate  \
0   2022-08-05 01:00:00  32.208611  70.495956  50.789150           0.003036   
1   2022-08-05 02:00:00  32.374252  71.371231  49.894035           0.003823   
2   2022-08-05 03:00:00  32.493065  72.135483  50.071583           0.003157   
3   2022-08-05 04:00:00  33.248547  72.015831  49.890583           0.002911   
4   2022-08-05 05:00:00  33.315788  72.254433  50.082134           0.004222   
..                  ...        ...        ...        ...                ...   
235 2022-08-14 20:00:00  46.159138  76.801140  50.079502           0.004221   
236 2022-08-14 21:00:00  49.993687  76.875786  50.070919           0.004314   
237 2022-08-14 22:00:00  52.738567  76.785690  50.023743           0.003544   
238 2022-08-14 23:00:00  52.779434  76.838661  49.929195           0.003215   
239 2022-08-15 00:00:00  52.931606  76.848816  49.894352           0.004399   

     Temp bearing  Temp bearing.1  Vibration (Feed)  Vibration (Driver)  \
0       37.991955       40.400871          0.107810            0.096917   
1       35.266655       36.967213          0.113241            0.103617   
2       33.619564       34.744221          0.104133            0.094712   
3       32.451893       33.493767          0.101984            0.084537   
4       31.904119       32.609093          0.102283            0.093264   
..            ...             ...               ...                 ...   
235     34.695885       33.076050          0.104000            0.093498   
236     34.007282       32.704453          0.106845            0.097706   
237     33.383522       32.179310          0.103860            0.091886   
238     32.820461       31.874279          0.107080            0.099006   
239     32.299679       31.490393          0.106721            0.093372   

     Vibration (Frame)  Blow speed (RPM)  Diff speed (RPM)  Torque (%)  \
0            -0.045779         -3.938236         -0.023145    0.187813   
1            -0.045776         -3.865058         -0.021069    0.159424   
2            -0.047202         -3.827369         -0.021001    0.144010   
3            -0.045751         -3.917721         -0.020724    0.143914   
4            -0.045662         -4.042665         -0.022636    0.125696   
..                 ...               ...               ...         ...   
235          -0.045883         -0.359330         -0.024723    0.118995   
236          -0.045880         -0.237000         -0.020543    0.113270   
237          -0.045776         -0.048069         -0.017303    0.120044   
238          -0.045866         -0.306246         -0.021945    0.119307   
239          -0.045776         -0.203180         -0.024231    0.125063   

     Severity  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
4         NaN  
..        ...  
235       NaN  
236       NaN  
237       NaN  
238       NaN  
239       NaN  

[240 rows x 14 columns]

In [34]:
X_submission = df_pred.iloc[:,1:13].to_numpy()

In [35]:
X_submission 

array([[ 3.22086105e+01,  7.04959564e+01,  5.07891502e+01, ...,
        -3.93823600e+00, -2.31453850e-02,  1.87813088e-01],
       [ 3.23742523e+01,  7.13712311e+01,  4.98940353e+01, ...,
        -3.86505818e+00, -2.10693800e-02,  1.59424007e-01],
       [ 3.24930649e+01,  7.21354828e+01,  5.00715828e+01, ...,
        -3.82736874e+00, -2.10011900e-02,  1.44010454e-01],
       ...,
       [ 5.27385673e+01,  7.67856903e+01,  5.00237427e+01, ...,
        -4.80686350e-02, -1.73026570e-02,  1.20044477e-01],
       [ 5.27794342e+01,  7.68386612e+01,  4.99291954e+01, ...,
        -3.06245983e-01, -2.19452190e-02,  1.19306542e-01],
       [ 5.29316063e+01,  7.68488159e+01,  4.98943520e+01, ...,
        -2.03179687e-01, -2.42310110e-02,  1.25062764e-01]])

In [36]:
X_submission = scaler.transform(X_submission) # Scale the test dataset

In [37]:
X_submission

array([[-1.60379806, -0.23343008, -0.44867586, ..., -1.10845571,
        -0.56611725, -0.78609248],
       [-1.59139676, -0.10184863, -0.53650684, ..., -1.10840945,
        -0.56461632, -0.79563802],
       [-1.58250148,  0.01304256, -0.51908543, ..., -1.10838562,
        -0.56456702, -0.80082066],
       ...,
       [-0.06675745,  0.71211575, -0.52377962, ..., -1.10599607,
        -0.56189303, -0.80887897],
       [-0.06369782,  0.72007895, -0.53305685, ..., -1.10615931,
        -0.56524954, -0.8091271 ],
       [-0.05230497,  0.72160552, -0.53647577, ..., -1.10609415,
        -0.56690214, -0.80719163]])

# Implement Phase for RFR

In [40]:
y_pred_sub_rfr = grid_search.predict(X_submission)

In [41]:
y_pred_sub_rfr

array([2.02195635, 2.05667857, 2.01291667, 2.00534524, 2.00066071,
       2.00275   , 2.02486905, 2.00416667, 2.00475   , 2.03085714,
       2.00454167, 2.02579167, 2.02702579, 2.01854762, 2.06472619,
       2.18022024, 2.21719643, 2.20392262, 2.0533869 , 2.05308333,
       2.05808333, 2.15277922, 2.05025   , 2.07520833, 2.153288  ,
       2.13968086, 2.18295238, 2.18373214, 2.18867316, 2.21461905,
       2.23966667, 2.19389286, 2.15080556, 2.19759722, 2.15858333,
       2.18708929, 2.2905496 , 2.3949623 , 2.52781349, 2.6878254 ,
       2.74919841, 2.38476371, 2.85169066, 2.85109542, 2.48416522,
       2.27697421, 2.34056133, 2.13941126, 2.185     , 2.20183333,
       2.20930357, 2.23826786, 2.3182123 , 2.32783532, 2.2574881 ,
       2.22910714, 2.97705952, 2.98120617, 2.97852976, 2.98351569,
       2.98116071, 2.98737284, 2.97614881, 2.98137121, 3.00345833,
       2.99991071, 2.99491071, 2.98487879, 2.99830952, 2.98465476,
       2.9907381 , 2.99049405, 2.98544444, 2.98048016, 2.97305

In [42]:
y_pred_sub_rfr = pd.Series(y_pred_sub_rfr, name='Severity')

In [43]:
df_submission_rfr = pd.concat([df_pred.iloc[:,:1], df_pred.iloc[:,1:13], pd.Series(y_pred_sub_rfr)], axis=1)

In [44]:
df_submission_rfr

Date     T-5551     T-5554     T-5552  Decanter Flowrate  \
0   2022-08-05 01:00:00  32.208611  70.495956  50.789150           0.003036   
1   2022-08-05 02:00:00  32.374252  71.371231  49.894035           0.003823   
2   2022-08-05 03:00:00  32.493065  72.135483  50.071583           0.003157   
3   2022-08-05 04:00:00  33.248547  72.015831  49.890583           0.002911   
4   2022-08-05 05:00:00  33.315788  72.254433  50.082134           0.004222   
..                  ...        ...        ...        ...                ...   
235 2022-08-14 20:00:00  46.159138  76.801140  50.079502           0.004221   
236 2022-08-14 21:00:00  49.993687  76.875786  50.070919           0.004314   
237 2022-08-14 22:00:00  52.738567  76.785690  50.023743           0.003544   
238 2022-08-14 23:00:00  52.779434  76.838661  49.929195           0.003215   
239 2022-08-15 00:00:00  52.931606  76.848816  49.894352           0.004399   

     Temp bearing  Temp bearing.1  Vibration (Feed)  Vibration (Driver)  \
0       37.991955       40.400871          0.107810            0.096917   
1       35.266655       36.967213          0.113241            0.103617   
2       33.619564       34.744221          0.104133            0.094712   
3       32.451893       33.493767          0.101984            0.084537   
4       31.904119       32.609093          0.102283            0.093264   
..            ...             ...               ...                 ...   
235     34.695885       33.076050          0.104000            0.093498   
236     34.007282       32.704453          0.106845            0.097706   
237     33.383522       32.179310          0.103860            0.091886   
238     32.820461       31.874279          0.107080            0.099006   
239     32.299679       31.490393          0.106721            0.093372   

     Vibration (Frame)  Blow speed (RPM)  Diff speed (RPM)  Torque (%)  \
0            -0.045779         -3.938236         -0.023145    0.187813   
1            -0.045776         -3.865058         -0.021069    0.159424   
2            -0.047202         -3.827369         -0.021001    0.144010   
3            -0.045751         -3.917721         -0.020724    0.143914   
4            -0.045662         -4.042665         -0.022636    0.125696   
..                 ...               ...               ...         ...   
235          -0.045883         -0.359330         -0.024723    0.118995   
236          -0.045880         -0.237000         -0.020543    0.113270   
237          -0.045776         -0.048069         -0.017303    0.120044   
238          -0.045866         -0.306246         -0.021945    0.119307   
239          -0.045776         -0.203180         -0.024231    0.125063   

     Severity  
0    2.021956  
1    2.056679  
2    2.012917  
3    2.005345  
4    2.000661  
..        ...  
235  2.149292  
236  2.134876  
237  2.116195  
238  2.173846  
239  2.147903  

[240 rows x 14 columns]

In [45]:
df_submission_rfr.tail(10)

Date     T-5551     T-5554     T-5552  Decanter Flowrate  \
230 2022-08-14 15:00:00  44.461311  76.533394  50.155449           0.004672   
231 2022-08-14 16:00:00  44.627338  76.591820  50.065979           0.003364   
232 2022-08-14 17:00:00  45.059555  76.605461  50.084969           0.004165   
233 2022-08-14 18:00:00  45.304211  76.675880  50.066841           0.004479   
234 2022-08-14 19:00:00  45.301586  76.735680  50.098618           0.003698   
235 2022-08-14 20:00:00  46.159138  76.801140  50.079502           0.004221   
236 2022-08-14 21:00:00  49.993687  76.875786  50.070919           0.004314   
237 2022-08-14 22:00:00  52.738567  76.785690  50.023743           0.003544   
238 2022-08-14 23:00:00  52.779434  76.838661  49.929195           0.003215   
239 2022-08-15 00:00:00  52.931606  76.848816  49.894352           0.004399   

     Temp bearing  Temp bearing.1  Vibration (Feed)  Vibration (Driver)  \
230     39.784660       35.335491          0.109485            0.096151   
231     38.544331       35.133545          0.108544            0.095577   
232     37.762901       34.945229          0.108082            0.100797   
233     36.801285       34.575352          0.111825            0.094992   
234     35.703705       33.821228          0.105990            0.094511   
235     34.695885       33.076050          0.104000            0.093498   
236     34.007282       32.704453          0.106845            0.097706   
237     33.383522       32.179310          0.103860            0.091886   
238     32.820461       31.874279          0.107080            0.099006   
239     32.299679       31.490393          0.106721            0.093372   

     Vibration (Frame)  Blow speed (RPM)  Diff speed (RPM)  Torque (%)  \
230          -0.051891         -0.365525         -0.020810    0.116730   
231          -0.050253         -0.336233         -0.020510    0.114278   
232          -0.048981         -0.425602         -0.019327    0.110466   
233          -0.048828         -0.453840         -0.021149    0.104884   
234          -0.048714         -0.404145         -0.018394    0.116226   
235          -0.045883         -0.359330         -0.024723    0.118995   
236          -0.045880         -0.237000         -0.020543    0.113270   
237          -0.045776         -0.048069         -0.017303    0.120044   
238          -0.045866         -0.306246         -0.021945    0.119307   
239          -0.045776         -0.203180         -0.024231    0.125063   

     Severity  
230  2.140898  
231  2.151324  
232  2.129461  
233  2.157015  
234  2.111125  
235  2.149292  
236  2.134876  
237  2.116195  
238  2.173846  
239  2.147903

In [46]:
df_submission_rfr.to_excel('20220819_20220805-20220515_NewDecanter_submission_rfr.xlsx', index=False) # Saving our submission file

# Export Model

In [ ]:
#import pickle

In [ ]:
#with open('S-1303A_BuildingModels_20210118_Standard.plk', 'wb') as f:
#    pickle.dump(clf_rfc, f)
## สร้าง pickle file 

In [51]:
# Saving the model
import pickle
pickle.dump(grid_search, open('GC6_Decanter_rfr.pkl', 'wb'))